from . import res_company
from . import res_config_settings
from . import hr_attendance
from . import ir_ui_view
from . import drawing_mixin
from . import hr_attendance_geofence
from . import ir_act_window_view
from . import ir_http
from . import hr_employee
from . import hr_attendance_reasons